# Generated by Django 5.1.6 on 2025-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboudi2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
