# Generated by Django 5.1.6 on 2025-02-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboudi2', '0002_alter_scholar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='scholar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='aboudi2.scholar'),
        ),
    ]
