# Generated by Django 5.1.6 on 2025-02-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboudi2', '0003_remove_scholar_playlists_playlist_scholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='aboudi2.scholar'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
