# Generated by Django 5.1.6 on 2025-02-12 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboudi2', '0005_remove_playlist_videos_video_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedvideo',
            name='download_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='local_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadedvideo',
            name='thumbnail_path',
            field=models.CharField(max_length=255),
        ),
    ]
